name: release image
on:
  push:
    tags:
      - 'image-v*' # push events for tags matching image-v for version (image-v1.0, etc)
permissions:
  contents: read
  packages: write
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        # retrieves latest tag name, snips string after first hyphen
        run: echo "RELEASE_VERSION=${$(git describe --abbrev=0)#*-}" >> $GITHUB_ENV
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/the-gophers/go-action:${{ env.RELEASE_VERSION }}
            ghcr.io/the-gophers/go-action:latest
